use std::fmt::Write;
use std::sync::LazyLock;

use super::brightness::{
    BRIGHTNESS_K, BRIGHTNESS_MAX_GAIN, BRIGHTNESS_ROLLOFF_HI, BRIGHTNESS_ROLLOFF_LO,
};
use super::color_grade::{
    COLOR_GRADE_FEATHER_BASE, COLOR_GRADE_FEATHER_RANGE, COLOR_GRADE_PIVOT_BASE,
    COLOR_GRADE_PIVOT_RANGE, COLOR_GRADE_STRENGTH,
};
use super::contrast::{CONTRAST_GAMMA, CONTRAST_ROLLOFF_HI, CONTRAST_ROLLOFF_LO};
use super::hsl::{
    HSL_BAND_CENTERS_DEG, HSL_BAND_SIGMA_DEG, HSL_HUE_SHIFT_DEG, HSL_INPUT_CEILING,
    HSL_LUM_SHIFT_SCALE, HSL_MIN_SAT, HSL_PARAM_FULL_SCALE, HSL_SAT_GATE_HI, HSL_SAT_GATE_LO,
};
use super::tone_regions::{
    TONE_REGIONS_BK_CEILING, TONE_REGIONS_BK_MASK_RANGE, TONE_REGIONS_BK_MULT_MAX,
    TONE_REGIONS_BK_STRENGTH, TONE_REGIONS_HL_DESAT_HI, TONE_REGIONS_HL_DESAT_LO,
    TONE_REGIONS_HL_MASK_HI, TONE_REGIONS_HL_MASK_LO, TONE_REGIONS_HL_MASK_TANH,
    TONE_REGIONS_HL_STRENGTH, TONE_REGIONS_SH_HALO_HI, TONE_REGIONS_SH_HALO_LO,
    TONE_REGIONS_SH_MASK_RANGE, TONE_REGIONS_SH_MULT_MAX, TONE_REGIONS_SH_MULT_MIN,
    TONE_REGIONS_SH_STRENGTH, TONE_REGIONS_WHITES_CLAMP, TONE_REGIONS_WHITES_SCALE,
};
use super::vibrance::{
    VIBRANCE_CHROMA_HI, VIBRANCE_CHROMA_LO, VIBRANCE_DESAT_HI, VIBRANCE_DESAT_LO, VIBRANCE_GAIN,
    VIBRANCE_SKIN_CHROMA_HI, VIBRANCE_SKIN_CHROMA_LO, VIBRANCE_SKIN_FACTOR, VIBRANCE_SKIN_HUE_DEG,
    VIBRANCE_SKIN_SPREAD_HI_DEG, VIBRANCE_SKIN_SPREAD_LO_DEG,
};
use crate::edits::HSL_BANDS;
use crate::wgsl::f32_lit;

const HUE_DIST: &str = r#"fn op_hue_dist(a: f32, b: f32) -> f32 {
    let raw = a - b;
    let wrapped = raw - floor(raw / 360.0) * 360.0;
    return min(wrapped, 360.0 - wrapped);
}
"#;

fn scalars(out: &mut String, entries: &[(&str, f32)]) {
    for (name, value) in entries {
        writeln!(out, "const {name}: f32 = {};", f32_lit(*value)).unwrap();
    }
}

static OP_PRELUDE_WGSL: LazyLock<String> = LazyLock::new(|| {
    let mut out = String::from(HUE_DIST);
    let centers = HSL_BAND_CENTERS_DEG
        .iter()
        .map(|v| f32_lit(*v))
        .collect::<Vec<String>>()
        .join(", ");
    writeln!(out, "const HSL_BANDS: i32 = {HSL_BANDS};").unwrap();
    writeln!(
        out,
        "const HSL_BAND_CENTERS_DEG: array<f32, {HSL_BANDS}> = array<f32, {HSL_BANDS}>({centers});"
    )
    .unwrap();
    scalars(
        &mut out,
        &[
            ("HSL_BAND_SIGMA_DEG", HSL_BAND_SIGMA_DEG),
            ("HSL_PARAM_FULL_SCALE", HSL_PARAM_FULL_SCALE),
            ("HSL_HUE_SHIFT_DEG", HSL_HUE_SHIFT_DEG),
            ("HSL_LUM_SHIFT_SCALE", HSL_LUM_SHIFT_SCALE),
            ("HSL_SAT_GATE_LO", HSL_SAT_GATE_LO),
            ("HSL_SAT_GATE_HI", HSL_SAT_GATE_HI),
            ("HSL_MIN_SAT", HSL_MIN_SAT),
            ("HSL_INPUT_CEILING", HSL_INPUT_CEILING),
            ("BRIGHTNESS_K", BRIGHTNESS_K),
            ("BRIGHTNESS_ROLLOFF_LO", BRIGHTNESS_ROLLOFF_LO),
            ("BRIGHTNESS_ROLLOFF_HI", BRIGHTNESS_ROLLOFF_HI),
            ("BRIGHTNESS_MAX_GAIN", BRIGHTNESS_MAX_GAIN),
            ("CONTRAST_GAMMA", CONTRAST_GAMMA),
            ("CONTRAST_ROLLOFF_LO", CONTRAST_ROLLOFF_LO),
            ("CONTRAST_ROLLOFF_HI", CONTRAST_ROLLOFF_HI),
            ("VIBRANCE_GAIN", VIBRANCE_GAIN),
            ("VIBRANCE_CHROMA_LO", VIBRANCE_CHROMA_LO),
            ("VIBRANCE_CHROMA_HI", VIBRANCE_CHROMA_HI),
            ("VIBRANCE_SKIN_HUE_DEG", VIBRANCE_SKIN_HUE_DEG),
            ("VIBRANCE_SKIN_SPREAD_LO_DEG", VIBRANCE_SKIN_SPREAD_LO_DEG),
            ("VIBRANCE_SKIN_SPREAD_HI_DEG", VIBRANCE_SKIN_SPREAD_HI_DEG),
            ("VIBRANCE_SKIN_CHROMA_LO", VIBRANCE_SKIN_CHROMA_LO),
            ("VIBRANCE_SKIN_CHROMA_HI", VIBRANCE_SKIN_CHROMA_HI),
            ("VIBRANCE_SKIN_FACTOR", VIBRANCE_SKIN_FACTOR),
            ("VIBRANCE_DESAT_LO", VIBRANCE_DESAT_LO),
            ("VIBRANCE_DESAT_HI", VIBRANCE_DESAT_HI),
            ("TONE_REGIONS_WHITES_CLAMP", TONE_REGIONS_WHITES_CLAMP),
            ("TONE_REGIONS_WHITES_SCALE", TONE_REGIONS_WHITES_SCALE),
            ("TONE_REGIONS_HL_MASK_LO", TONE_REGIONS_HL_MASK_LO),
            ("TONE_REGIONS_HL_MASK_HI", TONE_REGIONS_HL_MASK_HI),
            ("TONE_REGIONS_HL_MASK_TANH", TONE_REGIONS_HL_MASK_TANH),
            ("TONE_REGIONS_HL_STRENGTH", TONE_REGIONS_HL_STRENGTH),
            ("TONE_REGIONS_HL_DESAT_LO", TONE_REGIONS_HL_DESAT_LO),
            ("TONE_REGIONS_HL_DESAT_HI", TONE_REGIONS_HL_DESAT_HI),
            ("TONE_REGIONS_SH_MASK_RANGE", TONE_REGIONS_SH_MASK_RANGE),
            ("TONE_REGIONS_SH_HALO_LO", TONE_REGIONS_SH_HALO_LO),
            ("TONE_REGIONS_SH_HALO_HI", TONE_REGIONS_SH_HALO_HI),
            ("TONE_REGIONS_SH_STRENGTH", TONE_REGIONS_SH_STRENGTH),
            ("TONE_REGIONS_SH_MULT_MIN", TONE_REGIONS_SH_MULT_MIN),
            ("TONE_REGIONS_SH_MULT_MAX", TONE_REGIONS_SH_MULT_MAX),
            ("TONE_REGIONS_BK_CEILING", TONE_REGIONS_BK_CEILING),
            ("TONE_REGIONS_BK_MASK_RANGE", TONE_REGIONS_BK_MASK_RANGE),
            ("TONE_REGIONS_BK_STRENGTH", TONE_REGIONS_BK_STRENGTH),
            ("TONE_REGIONS_BK_MULT_MAX", TONE_REGIONS_BK_MULT_MAX),
            ("COLOR_GRADE_STRENGTH", COLOR_GRADE_STRENGTH),
            ("COLOR_GRADE_PIVOT_BASE", COLOR_GRADE_PIVOT_BASE),
            ("COLOR_GRADE_PIVOT_RANGE", COLOR_GRADE_PIVOT_RANGE),
            ("COLOR_GRADE_FEATHER_BASE", COLOR_GRADE_FEATHER_BASE),
            ("COLOR_GRADE_FEATHER_RANGE", COLOR_GRADE_FEATHER_RANGE),
        ],
    );
    out
});

pub fn op_prelude_wgsl() -> &'static str {
    &OP_PRELUDE_WGSL
}
