use crate::model::{ModelKind, ModelSpec};

use super::{CatalogEntry, CatalogFile, Cost, Tier};

pub const CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        id: "ormbg",
        name: "Open Remove Background",
        kind: ModelKind::Subject,
        tier: Tier::Recommended,
        url: "https://huggingface.co/schirrmacher/ormbg/resolve/main/ormbg.onnx",
        sha256: "89b47dd4fa46a76e91b06affeb5ec7881894a27792e41f7dfaf69987653f31d3",
        size_bytes: 176_182_050,
        aux: None,
        license: "Apache-2.0",
        source: "schirrmacher/ormbg",
        notes: "Soft per-strand alpha; keeps hair and small jewellery.",
        spec: ModelSpec::ORMBG,
        cost: Cost {
            gpu_ms: 742,
            gpu_mb: 431,
            cpu_ms: 6823,
            cpu_mb: 768,
        },
    },
    CatalogEntry {
        id: "u2netp",
        name: "U2-Net Lite",
        kind: ModelKind::Subject,
        tier: Tier::LowMemory,
        url: "https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2netp.onnx",
        sha256: "309c8469258dda742793dce0ebea8e6dd393174f89934733ecc8b14c76f4ddd8",
        size_bytes: 4_574_861,
        aux: None,
        license: "Apache-2.0",
        source: "xuebinqin/U-2-Net",
        notes: "320px only; blobby at high resolution. For constrained hosts.",
        spec: ModelSpec::U2NET,
        cost: Cost {
            gpu_ms: 116,
            gpu_mb: 68,
            cpu_ms: 774,
            cpu_mb: 233,
        },
    },
    CatalogEntry {
        id: "modnet",
        name: "MODNet",
        kind: ModelKind::People,
        tier: Tier::Recommended,
        url: "https://huggingface.co/onnx-community/modnet-webnn/resolve/main/onnx/model.onnx",
        sha256: "07c308cf0fc7e6e8b2065a12ed7fc07e1de8febb7dc7839d7b7f15dd66584df9",
        size_bytes: 25_888_640,
        aux: None,
        license: "Apache-2.0",
        source: "ZHKKKe/MODNet",
        notes: "Tuned for people. Softer edges around hair than the subject models, and the fastest model here.",
        spec: ModelSpec::MODNET,
        cost: Cost {
            gpu_ms: 140,
            gpu_mb: 122,
            cpu_ms: 195,
            cpu_mb: 196,
        },
    },
    CatalogEntry {
        id: "skyseg",
        name: "Sky Segmentation",
        kind: ModelKind::Sky,
        tier: Tier::Recommended,
        url: "https://huggingface.co/JianyuanWang/skyseg/resolve/main/skyseg.onnx",
        sha256: "ab9c34c64c3d821220a2886a4a06da4642ffa14d5b30e8d5339056a089aa1d39",
        size_bytes: 175_997_079,
        aux: None,
        license: "MIT",
        source: "xiongzhu666/Sky-Segmentation-and-Post-processing",
        notes: "Picks out sky for skies, horizons and reflections.",
        spec: ModelSpec::SKYSEG,
        cost: Cost {
            gpu_ms: 260,
            gpu_mb: 431,
            cpu_ms: 4207,
            cpu_mb: 406,
        },
    },
    CatalogEntry {
        id: "depth_anything_v2_vits",
        name: "Depth Anything V2 Small",
        kind: ModelKind::Depth,
        tier: Tier::LowMemory,
        url: "https://huggingface.co/CyberTimon/RapidRAW-Models/resolve/main/depth_anything_v2_vits.onnx",
        sha256: "d2b11a11c1d4a12b47608fa65a17ee9a4c605b55ee1730c8e3b526304f2562be",
        size_bytes: 99_373_606,
        aux: None,
        license: "Apache-2.0",
        source: "DepthAnything/Depth-Anything-V2",
        notes: "A quarter of the download and twice the speed of Base. Depth edges are softer.",
        spec: ModelSpec::DEPTH_ANYTHING,
        cost: Cost {
            gpu_ms: 339,
            gpu_mb: 284,
            cpu_ms: 2913,
            cpu_mb: 350,
        },
    },
    CatalogEntry {
        id: "depth_anything_v2_vitb",
        name: "Depth Anything V2 Base",
        kind: ModelKind::Depth,
        tier: Tier::Recommended,
        url: "https://huggingface.co/onnx-community/depth-anything-v2-base/resolve/main/onnx/model.onnx",
        sha256: "dab40f67d5ead5e0ed52acfae41a717a708b02bc57f6cb761c5de828f26a7289",
        size_bytes: 388_917_010,
        aux: None,
        license: "CC-BY-NC-4.0",
        source: "DepthAnything/Depth-Anything-V2",
        notes: "Estimates distance from camera, so you can mask by depth: near subject, mid ground, or far background.",
        spec: ModelSpec::DEPTH_ANYTHING,
        cost: Cost {
            gpu_ms: 873,
            gpu_mb: 761,
            cpu_ms: 1810,
            cpu_mb: 726,
        },
    },
    CatalogEntry {
        id: "segformer_b2_ade",
        name: "Scene Classes",
        kind: ModelKind::Semantic,
        tier: Tier::Recommended,
        url: "https://huggingface.co/Xenova/segformer-b2-finetuned-ade-512-512/resolve/main/onnx/model.onnx",
        sha256: "819c15e6af8c4de3359c1de7ab0a17d0dde495df1d16f8908a7163f8038e0fa0",
        size_bytes: 110_445_327,
        aux: None,
        license: "NVIDIA Source Code License (non-commercial)",
        source: "nvidia/segformer-b2-finetuned-ade-512-512",
        notes: "One model for sky, water, foliage, buildings, ground and people. Pick the class when you add the mask.",
        spec: ModelSpec::SEGFORMER_ADE,
        cost: Cost {
            gpu_ms: 332,
            gpu_mb: 371,
            cpu_ms: 527,
            cpu_mb: 752,
        },
    },
    CatalogEntry {
        id: "segformer_b0_ade",
        name: "Scene Classes Small",
        kind: ModelKind::Semantic,
        tier: Tier::LowMemory,
        url: "https://huggingface.co/Xenova/segformer-b0-finetuned-ade-512-512/resolve/main/onnx/model.onnx",
        sha256: "3e5c18a4be395f16646438d54c42377ddc202edfa33d5eced0c9506de75c44c2",
        size_bytes: 15_335_446,
        aux: None,
        license: "NVIDIA Source Code License (non-commercial)",
        source: "nvidia/segformer-b0-finetuned-ade-512-512",
        notes: "Same classes at a seventh of the download and four times the speed. Edges are looser on thin detail.",
        spec: ModelSpec::SEGFORMER_ADE,
        cost: Cost {
            gpu_ms: 71,
            gpu_mb: 133,
            cpu_ms: 109,
            cpu_mb: 251,
        },
    },
    CatalogEntry {
        id: "sam2_tiny",
        name: "SAM 2 Tiny",
        kind: ModelKind::Click,
        tier: Tier::Recommended,
        url: "https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_tiny.encoder.onnx",
        sha256: "4cc015ee18520e93f8c7ddfeaca7436039daaaaf19721b4b96a8810a805e82f7",
        size_bytes: 134_261_315,
        aux: Some(CatalogFile {
            url: "https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/resolve/main/sam2_hiera_tiny.decoder.onnx",
            sha256: "f5a4bd656c143899fb7f52d64ed81e6f6aeb37d477a0b6da50146ac7cf2187bf",
            size_bytes: 20_640_886,
        }),
        license: "Apache-2.0",
        source: "facebook/sam2-hiera-tiny",
        notes: "Click to add or remove parts of a mask. Follows edges more closely than MobileSAM, especially on hair and thin branches.",
        spec: ModelSpec::SAM,
        cost: Cost {
            gpu_ms: 729,
            gpu_mb: 417,
            cpu_ms: 3200,
            cpu_mb: 700,
        },
    },
    CatalogEntry {
        id: "mobilesam",
        name: "MobileSAM",
        kind: ModelKind::Click,
        tier: Tier::LowMemory,
        url: "https://huggingface.co/CyberTimon/RapidRAW-Models/resolve/main/vit_t_encoder.onnx",
        sha256: "8b8168033ea6687bb55ba242222b67a301ac9da30fd5cbfd04dcebbb180ec2a8",
        size_bytes: 28_106_845,
        aux: Some(CatalogFile {
            url: "https://huggingface.co/CyberTimon/RapidRAW-Models/resolve/main/vit_t_decoder.onnx",
            sha256: "1b216fb3b8ceeee00a65f89670c01e4c0d823fcacec39dd9accc233f85341dc4",
            size_bytes: 16_501_324,
        }),
        license: "Apache-2.0",
        source: "ChaoningZhang/MobileSAM",
        notes: "Click to add or remove parts of a mask. Encodes the photo once, then each click is fast.",
        spec: ModelSpec::SAM,
        cost: Cost {
            gpu_ms: 1131,
            gpu_mb: 512,
            cpu_ms: 4200,
            cpu_mb: 600,
        },
    },
];
