[package]
name = "ml"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
half = "2"
thiserror = { workspace = true }
tracing = { workspace = true }
ort = { version = "=2.0.0-rc.13", features = ["half"] }

[target.'cfg(not(all(target_arch = "aarch64", target_os = "linux")))'.dependencies]
ort = { version = "=2.0.0-rc.12", features = ["webgpu"] }
